version: "3.3"

services:
  rabbit:
    image: "rabbitmq:3.7.8-management-alpine"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  publisher:
    build:
      context: ./publisher
      dockerfile: ./docker/Dockerfile
    environment:
      RABBITMQ_USER: "rabbitmq"
      RABBITMQ_PASS: "rabbitmq"
      RABBITMQ_URL: "rabbit:5672"
      PUB_TOPIC: "townMessages"
    volumes:
      - ./publisher:/usr/src/app
      - publisher-node_modules:/usr/src/app/node_modules

  replay:
    build:
      context: ./replayer
      dockerfile: ./docker/Dockerfile
    environment:
      RABBITMQ_USER: "rabbitmq"
      RABBITMQ_PASS: "rabbitmq"
      RABBITMQ_URL: "rabbit:5672"
    volumes:
      - ./replayer:/usr/src/app
      - replayer-node_modules:/usr/src/app/node_modules

  event-store:
    build:
      context: ./event-store
      dockerfile: ./docker/Dockerfile
    environment:
      RABBITMQ_USER: "rabbitmq"
      RABBITMQ_PASS: "rabbitmq"
      RABBITMQ_URL: "rabbit:5672"
      SUB_TOPIC: "townMessages"
      DB_USER: "postgres"
      DB_PASS: "pass"
      DB_HOST: "pg"
      DB_NAME: "event_store"
    depends_on:
      - pg
    volumes:
      - ./event-store:/usr/src/app
      - event-store-node_modules:/usr/src/app/node_modules

  pg:
    image: postgres:10.6
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
      - "./event-store/db/pg-startup:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: "event_store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432

  subscriber:
    build:
      context: ./subscriber
      dockerfile: ./docker/Dockerfile
    environment:
      RABBITMQ_USER: "rabbitmq"
      RABBITMQ_PASS: "rabbitmq"
      RABBITMQ_URL: "rabbit:5672"
      SUB_TOPIC: "townMessages"
    volumes:
      - ./subscriber:/usr/src/app
      - subscriber-node_modules:/usr/src/app/node_modules

volumes:
  pg-data:
  rabbitmq-data:
  event-store-node_modules:
  subscriber-node_modules:
  publisher-node_modules:
  replayer-node_modules:
